# File: .github/workflows/workflow.yml

on:
  push:
    branches:
    - main

name: Deploy Azure Policies

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Microsoft.AAD/**
          policies/Microsoft.Compute/disks/**
          policies/Microsoft.Compute/virtualMachines/**
          policies/Microsoft.DBforMySQL/**
          policies/Microsoft.KeyVault/**
          policies/Microsoft.Sql/**
          initiatives/**
        assignments: assign.dev.json
        mode: incremental
    
    - name: Start Azure Policy Compliance Scan
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/dbacdf7c-cd4a-4866-8865-a4ef2c4c2499
        wait: false